/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  PanModel.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  12:19:16 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file contains the actual model variables and equations */

/* Note: Alias variables are the result of full optimization
   of the model in 20-sim. As a result, only the real variables
   are used in the model for speed. The user may also include
   the alias variables by adding them to the end of the array:

   XXDouble Pan_variables[NUMBER_VARIABLES + NUMBER_ALIAS_VARIABLES + 1];
   XXString Pan_variable_names[] = {
     VARIABLE_NAMES, ALIAS_VARIABLE_NAMES, NULL
   };

   and calculate them directly after the output equations:

   void PanCalculateOutput (void)
   {
     OUTPUT_EQUATIONS
     ALIAS_EQUATIONS
   }
*/

/* system include files */
#include <stdlib.h>
#include <math.h>
#include <string.h>

/* 20-sim include files */
#include "panmodel.h"
#include "xxfuncs.h"

/* the global variables */
XXDouble Pan_start_time = 0.0;
XXDouble Pan_finish_time = 20.0;
XXDouble Pan_step_size = 0.01;
XXDouble Pan_time = 0.0;
XXInteger Pan_steps = 0;
XXBoolean Pan_initialize = XXTRUE;
XXBoolean Pan_major = XXTRUE;
XXBoolean Pan_stop_simulation = XXFALSE;

/* the variable arrays */
XXDouble Pan_P[Pan_parameters_size];		/* parameters */
XXDouble Pan_I[Pan_initialvalues_size];		/* initial values */
XXDouble Pan_V[Pan_variables_size];		/* variables */
XXDouble Pan_s[Pan_states_size];		/* states */
XXDouble Pan_R[Pan_states_size];		/* rates (or new states) */

/* the names of the variables as used in the arrays above
   uncomment this part if these names are needed
XXString Pan_parameter_names[] = {
	"corrGain\\K",
	"PID1\\kp",
	"PID1\\tauD",
	"PID1\\beta",
	"PID1\\tauI",
	"SignalLimiter2\\minimum",
	"SignalLimiter2\\maximum"
,	NULL
};
XXString Pan_initial_value_names[] = {
	"PID1\\uD_previous_initial",
	"PID1\\error_previous_initial",
	"PID1\\uI_previous_initial"
,	NULL
};
XXString Pan_variable_names[] = {
	"corrGain\\corr",
	"PID1\\output",
	"",
	"PlusMinus1\\plus1",
	"SignalLimiter2\\output",
	"Splitter1\\input",
	"corr",
	"in",
	"position",
	"out"
,	NULL
};
XXString Pan_state_names[] = {
	"PID1\\uD_previous",
	"PID1\\error_previous",
	"PID1\\uI_previous"
,	NULL
};
XXString Pan_rate_names[] = {
	"",
	"PID1\\error",
	""
,	NULL
};
*/

#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", off)
#endif
void PanModelInitialize_parameters(void)
{
	/* set the parameters */
	Pan_P[0] = 0.0;		/* corrGain\K */
	Pan_P[1] = 2.6;		/* PID1\kp */
	Pan_P[2] = 0.05;		/* PID1\tauD */
	Pan_P[3] = 0.17;		/* PID1\beta */
	Pan_P[4] = 9.0;		/* PID1\tauI */
	Pan_P[5] = -0.99;		/* SignalLimiter2\minimum */
	Pan_P[6] = 0.99;		/* SignalLimiter2\maximum */

}
#if (7 > 8192) && defined _MSC_VER
#pragma optimize("", on)
#endif

void PanModelInitialize_initialvalues(void)
{
	/* set the initial values */
	Pan_I[0] = 0.0;		/* PID1\uD_previous_initial */
	Pan_I[1] = 0.0;		/* PID1\error_previous_initial */
	Pan_I[2] = 0.0;		/* PID1\uI_previous_initial */

}

void PanModelInitialize_states(void)
{
	/* set the states */
	Pan_s[0] = Pan_I[0];		/* PID1\uD_previous */
	Pan_s[1] = Pan_I[1];		/* PID1\error_previous */
	Pan_s[2] = Pan_I[2];		/* PID1\uI_previous */

}

void PanModelInitialize_variables(void)
{
	/* initialize the variable memory to zero */
	memset(Pan_V, 0, Pan_variables_size * sizeof(XXDouble));
}

/* this method is called before calculation is possible */
void PanModelInitialize (void)
{
	PanModelInitialize_parameters();
	PanModelInitialize_variables();
	PanModelInitialize_initialvalues();
	PanModelInitialize_states();
}

/* This function calculates the initial equations of the model.
 * These equations are calculated before anything else
 */
void PanCalculateInitial (void)
{

	/* set the states again, they might have changed in the initial calculation */
	PanModelInitialize_states ();
}

/* This function calculates the static equations of the model.
 * These equations are only dependent from parameters and constants
 */
void PanCalculateStatic (void)
{

}

/* This function calculates the input equations of the model.
 * These equations are dynamic equations that must not change
 * in calls from the integration method (like random and delay).
 */
void PanCalculateInput (void)
{

}

/* This function calculates the dynamic equations of the model.
 * These equations are called from the integration method
 * to calculate the new model rates (that are then integrated).
 */
void PanCalculateDynamic (void)
{
	/* PID1\factor = 1 / (sampletime + PID1\tauD * PID1\beta); */
	Pan_V[2] = 1.0 / (Pan_step_size + Pan_P[2] * Pan_P[3]);

	/* PlusMinus1\plus1 = in; */
	Pan_V[3] = Pan_V[7];

	/* Splitter1\input = position; */
	Pan_V[5] = Pan_V[8];

	/* corrGain\corr = corrGain\K * Splitter1\input; */
	Pan_V[0] = Pan_P[0] * Pan_V[5];

	/* PID1\error = PlusMinus1\plus1 - Splitter1\input; */
	Pan_R[1] = Pan_V[3] - Pan_V[5];

	/* PID1\uD = PID1\factor * (((PID1\tauD * PID1\uD_previous) * PID1\beta + (PID1\tauD * PID1\kp) * (PID1\error - PID1\error_previous)) + (sampletime * PID1\kp) * PID1\error); */
	Pan_R[0] = Pan_V[2] * (((Pan_P[2] * Pan_s[0]) * Pan_P[3] + (Pan_P[2] * Pan_P[1]) * (Pan_R[1] - Pan_s[1])) + (Pan_step_size * Pan_P[1]) * Pan_R[1]);

	/* PID1\uI = PID1\uI_previous + (sampletime * PID1\uD) / PID1\tauI; */
	Pan_R[2] = Pan_s[2] + (Pan_step_size * Pan_R[0]) / Pan_P[4];

	/* PID1\output = PID1\uI + PID1\uD; */
	Pan_V[1] = Pan_R[2] + Pan_R[0];

	/* SignalLimiter2\output = if PID1\output < SignalLimiter2\minimum... ; */
	Pan_V[4] = ((Pan_V[1] < Pan_P[5]) ? 
		/* SignalLimiter2\minimum */
		Pan_P[5]
	:
		/* if PID1\output > SignalLimiter2\maximum...  */
		((Pan_V[1] > Pan_P[6]) ? 
			/* SignalLimiter2\maximum */
			Pan_P[6]
		:
			/* PID1\output */
			Pan_V[1]
		)
	);


	/* increment the step counter */
	Pan_steps++;
}

/* This function calculates the output equations of the model.
 * These equations are not needed for calculation of the rates
 * and are kept separate to make the dynamic set of equations smaller.
 * These dynamic equations are called often more than one time for each
 * integration step that is taken. This makes model computation much faster.
 */
void PanCalculateOutput (void)
{
	/* corr = corrGain\corr; */
	Pan_V[6] = Pan_V[0];

	/* out = SignalLimiter2\output; */
	Pan_V[9] = Pan_V[4];

}

/* This function calculates the final equations of the model.
 * These equations are calculated after all the calculations
 * are performed
 */
void PanCalculateFinal (void)
{

}

/* this method is called after all calculations are performed */
void PanModelTerminate(void)
{
}

