/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  12:19:16 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "panmodel.h"
#include "xxfuncs.h"
#include "panmodel.h"
#include "motionprofiles.h"
#include "EulerAngles.h"

/* The submodel I/O variables */
XXInteger Pan_number_of_inputs = 2;
XXInteger Pan_number_of_outputs = 2;

extern XXDouble Pan_time;
extern XXDouble Pan_step_size;

#define Pan_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void PanDiscreteInitialize (void)
{
	/* nothing to be done */
	Pan_major = XXTRUE;
}

/* the termination of the Discrete integration method */
void PanDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void PanDiscreteStep (void)
{
	XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < Pan_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		Pan_s [index] = Pan_R [index];
	}
	/* increment the simulation time */
	Pan_time += Pan_step_size;

	Pan_major = XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	PanCalculateDynamic ();
}

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString Pan_input_names[] = {
	"in",
	"position"
,	NULL
};
XXString Pan_output_names[] = {
	"corr",
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void PanCopyInputsToVariables (XXDouble *u)
{
	/* Copy the input vector to the input variables */
	Pan_V[7] = u[0];		/* in */
	Pan_V[8] = u[1];		/* position */

}

/* This function uses the output variables to fill the output vector */
void PanCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	Pan_V[6];		/* corr */
	y[1] = 	Pan_V[9];		/* out */

}

/* The initialization function for submodel */
void PanInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	Pan_initialize = XXTRUE;
	Pan_steps = 0;
	PanModelInitialize ();
	PanDiscreteInitialize ();

	/* Copy the inputs */
	Pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	PanCalculateInitial ();
	PanCalculateStatic ();
	PanCalculateInput ();
	PanCalculateDynamic ();
	PanCalculateOutput ();

	/* Set the outputs */
	PanCopyVariablesToOutputs (y);

	/* End of initialization phase */
	Pan_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void PanCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	Pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the model */
	PanCalculateInput ();
	PanDiscreteStep ();
	PanCalculateOutput ();

	/* Copy the outputs */
	PanCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void PanTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	Pan_time = t;
	PanCopyInputsToVariables (u);

	/* Calculate the final model equations */
	PanCalculateFinal ();

	/* Set the outputs */
	PanCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	PanModelTerminate ();
	PanDiscreteTerminate ();
}

