/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerPan
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  12:19:16 PM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the PanModel.c file
*/

#ifndef PAN_SUBMOD_H
#define PAN_SUBMOD_H

/* Our own include files */
#include "panmodel.h"

/* Submodel I/O variables */
extern XXInteger Pan_number_of_inputs;
extern XXInteger Pan_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern XXString Pan_input_names[];
extern XXString Pan_output_names[];


/* The submodel functions */
void PanInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void PanCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void PanTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void PanCopyInputsToVariables (XXDouble *u);
void PanCopyVariablesToOutputs (XXDouble *y);

#endif

