/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  11:54:19 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the xxmodel.c file
*/

#ifndef TILT_SUBMOD_H
#define TILT_SUBMOD_H

/* Our own include files */
#include "tiltmodel.h"

/* Submodel I/O variables */
extern XXInteger tilt_number_of_inputs;
extern XXInteger tilt_number_of_outputs;

/* The names of the variables as used in the arrays above */
extern XXString tilt_input_names[];
extern XXString tilt_output_names[];


/* The submodel functions */
void TiltInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void TiltCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void TiltTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t);
void TiltCopyInputsToVariables (XXDouble *u);
void TiltCopyVariablesToOutputs (XXDouble *y);

#endif

