/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxsubmod.c
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  11:54:19 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* Standard include files */
#include <stdlib.h>

/* 20-sim include files */
#include "tiltmodel.h"
#include "xxfuncs.h"
#include "tiltmodel.h"
#include "motionprofiles.h"
#include "EulerAngles.h"

/* The submodel I/O variables */
XXInteger tilt_number_of_inputs = 3;
XXInteger tilt_number_of_outputs = 1;

extern XXDouble tilt_time;
extern XXDouble tilt_step_size;

#define tilt_STATE_SIZE 3

/*********************************************************************
 * Discrete integration method
 *********************************************************************/

/* the initialization of the Discrete integration method */
void TiltDiscreteInitialize (void)
{
	/* nothing to be done */
	tilt_major = XXTRUE;
}

/* the termination of the Discrete integration method */
void TiltDiscreteTerminate (void)
{
	/* nothing to be done */
}

/* the Discrete integration method itself */
void TiltDiscreteStep (void)
{
	XXInteger index;

	/* for each of the supplied states */
	for (index = 0; index < tilt_STATE_SIZE; index++)
	{
		/* just a move of the new state */
		tilt_s [index] = tilt_R [index];
	}
	/* increment the simulation time */
	tilt_time += tilt_step_size;

	tilt_major = XXTRUE;

	/* evaluate the dynamic part to calculate the new rates */
	TiltCalculateDynamic ();
}

/* the names of the submodel io variables
   uncomment this part if you need these names
XXString tilt_input_names[] = {
	"corr",
	"in",
	"position"
,	NULL
};
XXString tilt_output_names[] = {
	"out"
,	NULL
};
*/
/* This function sets the input variables from the input vector */
void TiltCopyInputsToVariables (XXDouble *u)
{
	/* Copy the inut vector to the input variables */
	tilt_V[8] = u[0];		/* corr */
	tilt_V[9] = u[1];		/* in */
	tilt_V[10] = u[2];		/* position */

}

/* This function uses the output variables to fill the output vector */
void TiltCopyVariablesToOutputs (XXDouble *y)
{
	/* Copy the output variables to the output vector */
	y[0] = 	tilt_V[11];		/* out */

}

/* The initialization function for submodel */
void TiltInitializeSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Initialization phase (allocating memory) */
	tilt_initialize = XXTRUE;
	tilt_steps = 0;
	TiltModelInitialize ();
	TiltDiscreteInitialize ();

	/* Copy the inputs */
	tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the model for the first time */
	TiltCalculateInitial ();
	TiltCalculateStatic ();
	TiltCalculateInput ();
	TiltCalculateDynamic ();
	TiltCalculateOutput ();

	/* Set the outputs */
	TiltCopyVariablesToOutputs (y);

	/* End of initialization phase */
	tilt_initialize = XXFALSE;
}

/* The function that calculates the submodel */
void TiltCalculateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the model */
	TiltCalculateInput ();
	TiltDiscreteStep ();
	TiltCalculateOutput ();

	/* Copy the outputs */
	TiltCopyVariablesToOutputs (y);
}

/* The termination function for submodel */
void TiltTerminateSubmodel (XXDouble *u, XXDouble *y, XXDouble t)
{
	/* Copy the inputs */
	tilt_time = t;
	TiltCopyInputsToVariables (u);

	/* Calculate the final model equations */
	TiltCalculateFinal ();

	/* Set the outputs */
	TiltCopyVariablesToOutputs (y);

	/* and terminate the model itself (releasing memory) */
	TiltModelTerminate ();
	TiltDiscreteTerminate ();
}

