/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  TiltModel.h
 *  subm:  PositionControllerTilt
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  11:54:19 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file describes the model functions
   that are supplied for computation.

   The model itself is the TiltModel.c file
*/

#ifndef tilt_MODEL_H
#define tilt_MODEL_H

/* Our own include files */
#include "xxtypes.h"

/* Simulation variables */
extern XXDouble tilt_start_time;
extern XXDouble tilt_finish_time;
extern XXDouble tilt_step_size;
extern XXDouble tilt_time;
extern XXInteger tilt_steps;
extern XXBoolean tilt_initialize;
extern XXBoolean tilt_major;
extern XXBoolean tilt_stop_simulation;

/* Model size constants */
#define tilt_constants_size 0
#define tilt_parameters_size 7
#define tilt_initialvalues_size 3
#define tilt_variables_size 12
#define tilt_states_size 3

/* Variable arrays */
extern XXDouble tilt_P[];
extern XXDouble tilt_I[];
extern XXDouble tilt_V[];
extern XXDouble tilt_s[];
extern XXDouble tilt_R[];


/* The names of the variables as used in the arrays above
   uncomment this if you need the names (see source file too)
extern XXString tilt_parameter_names[];
extern XXString tilt_initial_value_names[];
extern XXString tilt_variable_names[];
extern XXString tilt_state_names[];
extern XXString tilt_rate_names[];
*/

/* Initialization methods */
/* Initialize complete model */
void TiltModelInitialize (void);
/* Initialize specific model values */
void TiltModelInitialize_parameters(void);
void TiltModelInitialize_initialvalues(void);
void TiltModelInitialize_states(void);
void TiltModelInitialize_variables(void);
void TiltModelTerminate (void);

/* Computation methods */
void TiltCalculateInitial (void);
void TiltCalculateStatic (void);
void TiltCalculateInput (void);
void TiltCalculateDynamic (void);
void TiltCalculateOutput (void);
void TiltCalculateFinal (void);


#endif

