/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  motionprofiles.c
 *  model: Jiwy-1
 *  expmt: Jiwy-1
 *  date:  June 9, 2026
 *  time:  11:54:19 AM
 *  user:  20-sim 5.1 Professional
 *  from:  Demo/Viewer License
 *  build: 5.1.6.14106
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/

